ci: try to open a staging repo early

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -46,7 +46,76 @@ jobs:
               echo 'version=-PforceVersion="${{ steps.compute-next-version.outputs.next-version }}"' >> $GITHUB_OUTPUT
           fi
 
-  # Complete build, including testing, static analysis, and packaging
+  # Create a staging repository on Central
+  staging-repo:
+    runs-on: ubuntu-22.04
+    needs:
+      - ci-preparation
+    concurrency:
+      group: staging-repo-${{ needs.ci-preparation.outputs.build-ref }}
+    if: needs.ci-preparation.outputs.may-deploy
+    outputs:
+      repo-id: ${{ steps.staging-repo.outputs.MavenCentral }}
+    steps:
+      - name: Checkout the repo
+        uses: actions/checkout@v4.1.1
+      - uses: DanySK/build-check-deploy-gradle-action@2.2.17
+        with:
+          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+          should-run-codecov: false
+          should-deploy: true
+          build-command: true
+          check-command: true
+          deploy-command: |
+            ./gradlew ${{ needs.ci-preparation.outputs.force-version }} createStagingRepositoryOnMavenCentral --parallel
+      - name: Save the staging repository ID
+        id: staging-repo
+        run: |
+          [[ -f build/staging-repo-ids.properties ]] || (
+            echo "Staging repositories ID file not found" &&
+            exit 1
+          )
+          REPO_IDS=$(cat build/staging-repo-ids.properties)
+          echo "Staging repositories IDs:\n$REPO_IDS"
+          echo $REPO_IDS >> $GITHUB_OUTPUT
+
+  # Assemble all artifacts and upload them
+  assemble-and-upload:
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ windows-2022, macos-12, ubuntu-22.04 ]
+    runs-on: ${{ matrix.os }}
+    if: always() && !contains(needs.*.result, 'failure')
+    needs:
+      - ci-preparation
+      - staging-repo
+    concurrency:
+      group: assemble-and-upload-${{ needs.ci-preparation.outputs.build-ref }}
+    outputs:
+      maven-central-repo-id: ${{ steps.staging-repo.outputs.MavenCentral }}
+    steps:
+      - name: Checkout with full history
+        uses: danysk/action-checkout@0.2.14
+      - uses: DanySK/build-check-deploy-gradle-action@2.2.17
+        with:
+          signing-key: ${{ secrets.SIGNING_KEY }}
+          signing-password: ${{ secrets.SIGNING_PASSWORD }}
+          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+          should-run-codecov: false
+          should-deploy: ${{ contains('Linux', runner.os) }}
+          should-validate-wrapper: ${{ contains('Linux', runner.os) }}
+          build-command: |
+            ./gradlew ${{ needs.ci-preparation.outputs.force-version }} assemble --parallel
+          check-command: true
+          deploy-command: |
+            ./gradlew \
+            ${{ needs.ci-preparation.outputs.force-version }}\
+            -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }}\
+            uploadKotlinOSSRH uploadKotlinMultiplatform uploadJvm uploadJs --parallel\
+          clean-command: true
+
+  # Testing and static analysis
   build:
     needs:
       - ci-preparation
